### ISSUE TITLE
LookupError with Django 1.7 and an app without models.py

### ISSUE THREAD

**Issue by deschler** [toastdriven/django-haystack#1097]
I'm in the process of upgrading a project to Django 1.7. Rebuilding or updating the haystack index fails in combination with django-grappelli's dashboard. Please note, that in latest grappelli, the dashboard module/app doesn't have a models.py (which is allowed in Django 1.7 as far as i understand).
 
    $ ./manage.py rebuild_index
    
    WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
    Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
    Are you sure you wish to continue? [y/N] y
    Removing all documents from your index because you said so.
    All documents removed.
    ERROR:root:Error updating grappelli.dashboard using default 
    Traceback (most recent call last):
    File "/path/to/env/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 189, in handle_label
        self.update_backend(label, using)
    File "/path/to/env/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 203, in update_backend
        for model in get_models(label):
    File "/path/to/env/local/lib/python2.7/site-packages/haystack/utils/app_loading.py", line 41, in get_models
        return [apps.get_app_config(app_label).get_model(model_name)]
    File "/path/to/env/local/lib/python2.7/site-packages/django/apps/config.py", line 166, in get_model
        "App '%s' doesn't have a '%s' model." % (self.label, model_name))
    LookupError: App 'grappelli' doesn't have a 'dashboard' model.
    Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
    File "/path/to/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
    File "/path/to/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/path/to/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **options.__dict__)
    File "/path/to/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
        output = self.handle(*args, **options)
    File "/path/to/env/local/lib/python2.7/site-packages/haystack/management/commands/rebuild_index.py", line 16, in handle
        call_command('update_index', **options)
    File "/path/to/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
        return klass.execute(*args, **defaults)
    File "/path/to/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
        output = self.handle(*args, **options)
    File "/path/to/env/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 184, in handle
        return super(Command, self).handle(*items, **options)
    File "/path/to/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 503, in handle
        label_output = self.handle_label(label, **options)
    File "/path/to/env/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 189, in handle_label
        self.update_backend(label, using)
    File "/path/to/env/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 203, in update_backend
        for model in get_models(label):
    File "/path/to/env/local/lib/python2.7/site-packages/haystack/utils/app_loading.py", line 41, in get_models
        return [apps.get_app_config(app_label).get_model(model_name)]
    File "/path/to/env/local/lib/python2.7/site-packages/django/apps/config.py", line 166, in get_model
        "App '%s' doesn't have a '%s' model." % (self.label, model_name))
    LookupError: App 'grappelli' doesn't have a 'dashboard' model.

Django: 1.7.1
django-haystack: 2.3.1
django-grappelli: 2.6.2
 
    INSTALLED_APPS = (
        'grappelli.dashboard',
        'grappelli',
        # ...
        'haystack',
    )

The management command works when `'grappelli.dashboard'` is removed from INSTALLED_APPS.

**Comment by ikks** [comment]
@ctrl-alt-delete thank you, it works with @deschler fix.

**Comment by camilonova** [comment]
Any updates here to have it fixed?

**Comment by chazmead** [comment]
Yes, I could do with this being fixed in the actual project, as we use
auto-deployment on scalable servers, and I don't want to be manually
installing dist-packages everytime we add new servers....

Thanks.

**Comment by acdha** [comment]
@camilonova @chazmead Have you tested @deschler's patch in https://github.com/toastdriven/django-haystack/pull/1124 and, if so, how did it go?

**Comment by chazmead** [comment]
AS I said... i don't want to have to patch it, i need it to be installable
via pip as we use automatic deployment across horizontally scaled servers,
and I don't want to have to patch each server every time we bring a new one
online...  and I also don't want to have to bootstrap extra deployment
steps just for haystack.. it would be nice if it just worked from the
package manager...

**Comment by camilonova** [comment]
@acdha Works fine, please merge it.

**Comment by acdha** [comment]
@chazmead We're all volunteers working on this project. Helping with the testing makes the process of merging things into the next PyPI release faster.

**Comment by chazmead** [comment]
I understand that, I was merely asking whether there was any update with
when it may be merged, and people kept telling me to use another fork...
and I had to iterate that this solution is not suitable for my situation.

Thanks.

**Comment by acdha** [comment]
@camilonova It's merged on acdha/django-haystack – the CI build passed everything except for the unrelated #1001 failures so I'll merge it into master shortly.

**Comment by camilonova** [comment]
@acdha can you merge it into master since it does not affect the open ticket. If you merge it will be one less ticket open instead of two.

I'm afraid to wait for weeks to see this happening.

**Comment by acdha** [comment]
@chazmead When those other people are maintainers asking for help testing, consider that they might in fact be working towards the same goal.

**Comment by chazmead** [comment]
No one asked for my help to test, they said "it works on this other fork,
use that." ...

**Comment by camilonova** [comment]
Just for the record this was fixed here https://github.com/toastdriven/django-haystack/commit/4dd7d998d7277bf3119b553dcb3dcdcf11b1f335

@acdha Thank you

**Comment by camilonova** [comment]
@acdha can you issue a release including this?

**Comment by acdha** [comment]
@camilonova That's the plan – I'd like to get 2.4 out at some point soon.

**Comment by camilonova** [comment]
days, weeks?

**Comment by acdha** [comment]
Good question – I think much of what's in https://github.com/toastdriven/django-haystack/milestones/v2.4.0 should be pushed to a later milestone but I'd like to get at least https://github.com/toastdriven/django-haystack/issues/1133 taken care of.

**Comment by troygrosfield** [comment]
PR is out for the doc for #1133:

- https://github.com/toastdriven/django-haystack/pull/1139

**Comment by camilonova** [comment]
@acdha Chris seems the PR was merged, can we make this one as resolved?

**Comment by acdha** [comment]
@camilonova Yes, this should be ready to go shortly. Have you had the chance to test the current master branch?

**Comment by camilonova** [comment]
@acdha Not recently, like most brave man I like to test on production.

**Comment by troygrosfield** [comment]
@acdha, I've been running locally with Django 1.7 python 3.4 without issues using the master branch.

**Comment by acdha** [comment]
There's a release candidate on PyPI now:

pip install django-haystack==2.4.0rc1

**Comment by chazmead** [comment]
Thank you, please advise when this RC has become a release version.

Much appreciated.

**Comment by acdha** [comment]
I'm planning to release this fairly soon but would like to get feedback from people who've tested the release candidate on their projects to confirm that there aren't any significant gaps in my testing.

**Comment by chazmead** [comment]
Ok, I will update my development environment, and run tests.

**Comment by chazmead** [comment]
No errors on my side.

Good work.  I'll hold off putting on production till a full version is
released.

Thanks again.

**Comment by acdha** [comment]
Great, thanks for the rapid response!
