### ISSUE TITLE
Description on  github is out of date

### ISSUE THREAD

**Issue by pombredanne** [toastdriven/django-haystack#1116]
"Modular search for Django. Currently v2.1.1-dev. "
The current version is no longer 2.1.1-dev ;)

**Comment by rafalp** [comment]
Perhaps main repo could be transfered to organization?

Looking at @toastdriven activity on github, it looks like he took break from Github and only recently started working on new project.

**Comment by SalahAdDin** [comment]
Is very important that @toastdriven change the admin of this repo, for the new admin update haystack, haystack is a very good project.

**Comment by toastdriven** [comment]
Description updated and all back versions of the docs built. I don't know why RtD isn't picking up the new tags like it should. http://django-haystack.readthedocs.org/en/v2.3.1/

**Comment by toastdriven** [comment]
Oh, and @acdha is now a maintainer on the django-haystack RtD package.

**Comment by SalahAdDin** [comment]
ok, thank you very much @toastdriven, i like django-haystack, is a good app.
