### ISSUE TITLE
Include py34-django1.7 in .travis.yml 

### ISSUE THREAD

**Issue by troygrosfield** [toastdriven/django-haystack#1131]
I see the ``py34-django1.7`` environment added in ``tox.ini``, but I don't see it included in ``.travis.yml``.  Any reason tests aren't being run against py34-django1.7?

**Comment by acdha** [comment]
IIRC, at the time Travis didn't support Python 3.4. If they've rolled that out we should definitely add it.

**Comment by troygrosfield** [comment]
Added it to PR #1130 via:

- https://github.com/toastdriven/django-haystack/commit/4869be0784f8e09bcaf7fde66f2901ef13ca4050
