### ISSUE TITLE
Align with 1.3 Class-based Views?

### ISSUE THREAD

**Issue by typeshige** [toastdriven/django-haystack#350]
I've been using class-based views since 1.3 came out and I see that Haystack's SearchView is pretty similar but different enough that I need to keep checking the docs.

Do you plan or think it's a good idea to make it more similar?

For example in haystack:

    template = 'example.html'
    def extra_context(self):
        context = super(MyClass, self).extra_context()
        return context

In class-based views:

    template_name = 'example.html'
    def get_context_data(self, **kwargs):
        context = super(MyClass, self).get_context_data(**kwargs)
        return context

**Comment by acdha** [comment]
There's a release candidate on PyPI now which includes the new generic views added in #1130:

pip install django-haystack==2.4.0rc1
